file:
  upload-dir: uploads

spring:
  mail:
    host: smtp.qq.com
    username: 3499508634@qq.com
    password: woxncrbagfibdbif
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: G7v!p9Xq$2RfL8kM
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update      # 自动建表或更新表结构
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# WebSocket configuration
websocket:
  allowed-origins: http://localhost:3000,http://localhost:8080

# 可选日志配置
logging:
  level:
    root: INFO
    org.springframework: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Spring Boot Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true
    rabbit:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name:horizon}
      environment: ${spring.profiles.active:default}

# Application info for /actuator/info
info:
  app:
    name: Horizon Blog System
    description: A professional blog management system
    version: 0.0.1-SNAPSHOT
    encoding: ${project.build.sourceEncoding:UTF-8}
    java:
      version: ${java.version:24}

# 可选 OpenAPI / Swagger 配置
# springdoc:
#   api-docs:
#     path: /v3/api-docs
#   swagger-ui:
#     path: /swagger-ui.html
#     enabled: true
#     operationsSorter: method
#   show-actuat: true
